# Generated by Django 4.2.30 on 2026-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='whatsapp',
            field=models.CharField(blank=True, default='#', max_length=50),
        ),
    ]
